// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "paultio/ros-go/msgs/std_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/geo_point_stamped.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GeoPointStamped", GeoPointStampedTypeSupport)
	typemap.RegisterMessage("geographic_msgs/msg/GeoPointStamped", GeoPointStampedTypeSupport)
}

type GeoPointStamped struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Position GeoPoint `yaml:"position"`
}

// NewGeoPointStamped creates a new GeoPointStamped with default values.
func NewGeoPointStamped() *GeoPointStamped {
	self := GeoPointStamped{}
	self.SetDefaults()
	return &self
}

func (t *GeoPointStamped) Clone() *GeoPointStamped {
	c := &GeoPointStamped{}
	c.Header = *t.Header.Clone()
	c.Position = *t.Position.Clone()
	return c
}

func (t *GeoPointStamped) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GeoPointStamped) SetDefaults() {
	t.Header.SetDefaults()
	t.Position.SetDefaults()
}

func (t *GeoPointStamped) GetTypeSupport() types.MessageTypeSupport {
	return GeoPointStampedTypeSupport
}

// GeoPointStampedPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GeoPointStampedPublisher struct {
	*rclgo.Publisher
}

// NewGeoPointStampedPublisher creates and returns a new publisher for the
// GeoPointStamped
func NewGeoPointStampedPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GeoPointStampedPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GeoPointStampedTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GeoPointStampedPublisher{pub}, nil
}

func (p *GeoPointStampedPublisher) Publish(msg *GeoPointStamped) error {
	return p.Publisher.Publish(msg)
}

// GeoPointStampedSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GeoPointStampedSubscription struct {
	*rclgo.Subscription
}

// GeoPointStampedSubscriptionCallback type is used to provide a subscription
// handler function for a GeoPointStampedSubscription.
type GeoPointStampedSubscriptionCallback func(msg *GeoPointStamped, info *rclgo.MessageInfo, err error)

// NewGeoPointStampedSubscription creates and returns a new subscription for the
// GeoPointStamped
func NewGeoPointStampedSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GeoPointStampedSubscriptionCallback) (*GeoPointStampedSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GeoPointStamped
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GeoPointStampedTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GeoPointStampedSubscription{sub}, nil
}

func (s *GeoPointStampedSubscription) TakeMessage(out *GeoPointStamped) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGeoPointStampedSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGeoPointStampedSlice(dst, src []GeoPointStamped) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GeoPointStampedTypeSupport types.MessageTypeSupport = _GeoPointStampedTypeSupport{}

type _GeoPointStampedTypeSupport struct{}

func (t _GeoPointStampedTypeSupport) New() types.Message {
	return NewGeoPointStamped()
}

func (t _GeoPointStampedTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__GeoPointStamped
	return (unsafe.Pointer)(C.geographic_msgs__msg__GeoPointStamped__create())
}

func (t _GeoPointStampedTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__GeoPointStamped__destroy((*C.geographic_msgs__msg__GeoPointStamped)(pointer_to_free))
}

func (t _GeoPointStampedTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GeoPointStamped)
	mem := (*C.geographic_msgs__msg__GeoPointStamped)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	GeoPointTypeSupport.AsCStruct(unsafe.Pointer(&mem.position), &m.Position)
}

func (t _GeoPointStampedTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GeoPointStamped)
	mem := (*C.geographic_msgs__msg__GeoPointStamped)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	GeoPointTypeSupport.AsGoStruct(&m.Position, unsafe.Pointer(&mem.position))
}

func (t _GeoPointStampedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__GeoPointStamped())
}

type CGeoPointStamped = C.geographic_msgs__msg__GeoPointStamped
type CGeoPointStamped__Sequence = C.geographic_msgs__msg__GeoPointStamped__Sequence

func GeoPointStamped__Sequence_to_Go(goSlice *[]GeoPointStamped, cSlice CGeoPointStamped__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GeoPointStamped, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GeoPointStampedTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GeoPointStamped__Sequence_to_C(cSlice *CGeoPointStamped__Sequence, goSlice []GeoPointStamped) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__GeoPointStamped)(C.malloc(C.sizeof_struct_geographic_msgs__msg__GeoPointStamped * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GeoPointStampedTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GeoPointStamped__Array_to_Go(goSlice []GeoPointStamped, cSlice []CGeoPointStamped) {
	for i := 0; i < len(cSlice); i++ {
		GeoPointStampedTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GeoPointStamped__Array_to_C(cSlice []CGeoPointStamped, goSlice []GeoPointStamped) {
	for i := 0; i < len(goSlice); i++ {
		GeoPointStampedTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
