// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "paultio/ros-go/msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/map_feature.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/MapFeature", MapFeatureTypeSupport)
	typemap.RegisterMessage("geographic_msgs/msg/MapFeature", MapFeatureTypeSupport)
}

type MapFeature struct {
	Id unique_identifier_msgs_msg.UUID `yaml:"id"`// Unique feature identifier
	Components []unique_identifier_msgs_msg.UUID `yaml:"components"`// Sequence of feature components
	Props []KeyValue `yaml:"props"`// Key/value properties for this feature
}

// NewMapFeature creates a new MapFeature with default values.
func NewMapFeature() *MapFeature {
	self := MapFeature{}
	self.SetDefaults()
	return &self
}

func (t *MapFeature) Clone() *MapFeature {
	c := &MapFeature{}
	c.Id = *t.Id.Clone()
	if t.Components != nil {
		c.Components = make([]unique_identifier_msgs_msg.UUID, len(t.Components))
		unique_identifier_msgs_msg.CloneUUIDSlice(c.Components, t.Components)
	}
	if t.Props != nil {
		c.Props = make([]KeyValue, len(t.Props))
		CloneKeyValueSlice(c.Props, t.Props)
	}
	return c
}

func (t *MapFeature) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MapFeature) SetDefaults() {
	t.Id.SetDefaults()
	t.Components = nil
	t.Props = nil
}

func (t *MapFeature) GetTypeSupport() types.MessageTypeSupport {
	return MapFeatureTypeSupport
}

// MapFeaturePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MapFeaturePublisher struct {
	*rclgo.Publisher
}

// NewMapFeaturePublisher creates and returns a new publisher for the
// MapFeature
func NewMapFeaturePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MapFeaturePublisher, error) {
	pub, err := node.NewPublisher(topic_name, MapFeatureTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MapFeaturePublisher{pub}, nil
}

func (p *MapFeaturePublisher) Publish(msg *MapFeature) error {
	return p.Publisher.Publish(msg)
}

// MapFeatureSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MapFeatureSubscription struct {
	*rclgo.Subscription
}

// MapFeatureSubscriptionCallback type is used to provide a subscription
// handler function for a MapFeatureSubscription.
type MapFeatureSubscriptionCallback func(msg *MapFeature, info *rclgo.MessageInfo, err error)

// NewMapFeatureSubscription creates and returns a new subscription for the
// MapFeature
func NewMapFeatureSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MapFeatureSubscriptionCallback) (*MapFeatureSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MapFeature
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MapFeatureTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MapFeatureSubscription{sub}, nil
}

func (s *MapFeatureSubscription) TakeMessage(out *MapFeature) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMapFeatureSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMapFeatureSlice(dst, src []MapFeature) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MapFeatureTypeSupport types.MessageTypeSupport = _MapFeatureTypeSupport{}

type _MapFeatureTypeSupport struct{}

func (t _MapFeatureTypeSupport) New() types.Message {
	return NewMapFeature()
}

func (t _MapFeatureTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__MapFeature
	return (unsafe.Pointer)(C.geographic_msgs__msg__MapFeature__create())
}

func (t _MapFeatureTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__MapFeature__destroy((*C.geographic_msgs__msg__MapFeature)(pointer_to_free))
}

func (t _MapFeatureTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MapFeature)
	mem := (*C.geographic_msgs__msg__MapFeature)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.id), &m.Id)
	unique_identifier_msgs_msg.UUID__Sequence_to_C((*unique_identifier_msgs_msg.CUUID__Sequence)(unsafe.Pointer(&mem.components)), m.Components)
	KeyValue__Sequence_to_C(&mem.props, m.Props)
}

func (t _MapFeatureTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MapFeature)
	mem := (*C.geographic_msgs__msg__MapFeature)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.Id, unsafe.Pointer(&mem.id))
	unique_identifier_msgs_msg.UUID__Sequence_to_Go(&m.Components, *(*unique_identifier_msgs_msg.CUUID__Sequence)(unsafe.Pointer(&mem.components)))
	KeyValue__Sequence_to_Go(&m.Props, mem.props)
}

func (t _MapFeatureTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__MapFeature())
}

type CMapFeature = C.geographic_msgs__msg__MapFeature
type CMapFeature__Sequence = C.geographic_msgs__msg__MapFeature__Sequence

func MapFeature__Sequence_to_Go(goSlice *[]MapFeature, cSlice CMapFeature__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MapFeature, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MapFeatureTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MapFeature__Sequence_to_C(cSlice *CMapFeature__Sequence, goSlice []MapFeature) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__MapFeature)(C.malloc(C.sizeof_struct_geographic_msgs__msg__MapFeature * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MapFeatureTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MapFeature__Array_to_Go(goSlice []MapFeature, cSlice []CMapFeature) {
	for i := 0; i < len(cSlice); i++ {
		MapFeatureTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MapFeature__Array_to_C(cSlice []CMapFeature, goSlice []MapFeature) {
	for i := 0; i < len(goSlice); i++ {
		MapFeatureTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
