// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "paultio/ros-go/msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/way_point.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/WayPoint", WayPointTypeSupport)
	typemap.RegisterMessage("geographic_msgs/msg/WayPoint", WayPointTypeSupport)
}

type WayPoint struct {
	Id unique_identifier_msgs_msg.UUID `yaml:"id"`// Unique way-point identifier
	Position GeoPoint `yaml:"position"`// Position relative to WGS 84 ellipsoid
	Props []KeyValue `yaml:"props"`// Key/value properties for this point
}

// NewWayPoint creates a new WayPoint with default values.
func NewWayPoint() *WayPoint {
	self := WayPoint{}
	self.SetDefaults()
	return &self
}

func (t *WayPoint) Clone() *WayPoint {
	c := &WayPoint{}
	c.Id = *t.Id.Clone()
	c.Position = *t.Position.Clone()
	if t.Props != nil {
		c.Props = make([]KeyValue, len(t.Props))
		CloneKeyValueSlice(c.Props, t.Props)
	}
	return c
}

func (t *WayPoint) CloneMsg() types.Message {
	return t.Clone()
}

func (t *WayPoint) SetDefaults() {
	t.Id.SetDefaults()
	t.Position.SetDefaults()
	t.Props = nil
}

func (t *WayPoint) GetTypeSupport() types.MessageTypeSupport {
	return WayPointTypeSupport
}

// WayPointPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type WayPointPublisher struct {
	*rclgo.Publisher
}

// NewWayPointPublisher creates and returns a new publisher for the
// WayPoint
func NewWayPointPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*WayPointPublisher, error) {
	pub, err := node.NewPublisher(topic_name, WayPointTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &WayPointPublisher{pub}, nil
}

func (p *WayPointPublisher) Publish(msg *WayPoint) error {
	return p.Publisher.Publish(msg)
}

// WayPointSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type WayPointSubscription struct {
	*rclgo.Subscription
}

// WayPointSubscriptionCallback type is used to provide a subscription
// handler function for a WayPointSubscription.
type WayPointSubscriptionCallback func(msg *WayPoint, info *rclgo.MessageInfo, err error)

// NewWayPointSubscription creates and returns a new subscription for the
// WayPoint
func NewWayPointSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback WayPointSubscriptionCallback) (*WayPointSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg WayPoint
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, WayPointTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &WayPointSubscription{sub}, nil
}

func (s *WayPointSubscription) TakeMessage(out *WayPoint) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneWayPointSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneWayPointSlice(dst, src []WayPoint) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var WayPointTypeSupport types.MessageTypeSupport = _WayPointTypeSupport{}

type _WayPointTypeSupport struct{}

func (t _WayPointTypeSupport) New() types.Message {
	return NewWayPoint()
}

func (t _WayPointTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__WayPoint
	return (unsafe.Pointer)(C.geographic_msgs__msg__WayPoint__create())
}

func (t _WayPointTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__WayPoint__destroy((*C.geographic_msgs__msg__WayPoint)(pointer_to_free))
}

func (t _WayPointTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*WayPoint)
	mem := (*C.geographic_msgs__msg__WayPoint)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.id), &m.Id)
	GeoPointTypeSupport.AsCStruct(unsafe.Pointer(&mem.position), &m.Position)
	KeyValue__Sequence_to_C(&mem.props, m.Props)
}

func (t _WayPointTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*WayPoint)
	mem := (*C.geographic_msgs__msg__WayPoint)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.Id, unsafe.Pointer(&mem.id))
	GeoPointTypeSupport.AsGoStruct(&m.Position, unsafe.Pointer(&mem.position))
	KeyValue__Sequence_to_Go(&m.Props, mem.props)
}

func (t _WayPointTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__WayPoint())
}

type CWayPoint = C.geographic_msgs__msg__WayPoint
type CWayPoint__Sequence = C.geographic_msgs__msg__WayPoint__Sequence

func WayPoint__Sequence_to_Go(goSlice *[]WayPoint, cSlice CWayPoint__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]WayPoint, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		WayPointTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func WayPoint__Sequence_to_C(cSlice *CWayPoint__Sequence, goSlice []WayPoint) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__WayPoint)(C.malloc(C.sizeof_struct_geographic_msgs__msg__WayPoint * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		WayPointTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func WayPoint__Array_to_Go(goSlice []WayPoint, cSlice []CWayPoint) {
	for i := 0; i < len(cSlice); i++ {
		WayPointTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func WayPoint__Array_to_C(cSlice []CWayPoint, goSlice []WayPoint) {
	for i := 0; i < len(goSlice); i++ {
		WayPointTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
