// Code generated by rclgo-gen. DO NOT EDIT.

package msgs

import (
	_ "paultio/ros-go/msgs/action_msgs/msg" //
	_ "paultio/ros-go/msgs/action_msgs/srv" //
	_ "paultio/ros-go/msgs/actionlib_msgs/msg" //
	_ "paultio/ros-go/msgs/builtin_interfaces/msg" //
	_ "paultio/ros-go/msgs/composition_interfaces/srv" //
	_ "paultio/ros-go/msgs/diagnostic_msgs/msg" //
	_ "paultio/ros-go/msgs/diagnostic_msgs/srv" //
	_ "paultio/ros-go/msgs/geographic_msgs/msg" //
	_ "paultio/ros-go/msgs/geographic_msgs/srv" //
	_ "paultio/ros-go/msgs/geometry_msgs/msg" //
	_ "paultio/ros-go/msgs/lifecycle_msgs/msg" //
	_ "paultio/ros-go/msgs/lifecycle_msgs/srv" //
	_ "paultio/ros-go/msgs/nav_msgs/msg" //
	_ "paultio/ros-go/msgs/nav_msgs/srv" //
	_ "paultio/ros-go/msgs/rcl_interfaces/msg" //
	_ "paultio/ros-go/msgs/rcl_interfaces/srv" //
	_ "paultio/ros-go/msgs/rmw_dds_common/msg" //
	_ "paultio/ros-go/msgs/rosbag2_interfaces/msg" //
	_ "paultio/ros-go/msgs/rosbag2_interfaces/srv" //
	_ "paultio/ros-go/msgs/rosgraph_msgs/msg" //
	_ "paultio/ros-go/msgs/sensor_msgs/msg" //
	_ "paultio/ros-go/msgs/sensor_msgs/srv" //
	_ "paultio/ros-go/msgs/shape_msgs/msg" //
	_ "paultio/ros-go/msgs/statistics_msgs/msg" //
	_ "paultio/ros-go/msgs/std_msgs/msg" //
	_ "paultio/ros-go/msgs/std_srvs/srv" //
	_ "paultio/ros-go/msgs/stereo_msgs/msg" //
	_ "paultio/ros-go/msgs/tf2_msgs/action" //
	_ "paultio/ros-go/msgs/tf2_msgs/msg" //
	_ "paultio/ros-go/msgs/tf2_msgs/srv" //
	_ "paultio/ros-go/msgs/trajectory_msgs/msg" //
	_ "paultio/ros-go/msgs/unique_identifier_msgs/msg" //
	_ "paultio/ros-go/msgs/visualization_msgs/msg" //
	_ "paultio/ros-go/msgs/visualization_msgs/srv" //
)
