// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geographic_msgs_msg "paultio/ros-go/msgs/geographic_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/srv/get_geo_path.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GetGeoPath_Request", GetGeoPath_RequestTypeSupport)
	typemap.RegisterMessage("geographic_msgs/srv/GetGeoPath_Request", GetGeoPath_RequestTypeSupport)
}

type GetGeoPath_Request struct {
	Start geographic_msgs_msg.GeoPoint `yaml:"start"`// starting point
	Goal geographic_msgs_msg.GeoPoint `yaml:"goal"`// goal point
}

// NewGetGeoPath_Request creates a new GetGeoPath_Request with default values.
func NewGetGeoPath_Request() *GetGeoPath_Request {
	self := GetGeoPath_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetGeoPath_Request) Clone() *GetGeoPath_Request {
	c := &GetGeoPath_Request{}
	c.Start = *t.Start.Clone()
	c.Goal = *t.Goal.Clone()
	return c
}

func (t *GetGeoPath_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetGeoPath_Request) SetDefaults() {
	t.Start.SetDefaults()
	t.Goal.SetDefaults()
}

func (t *GetGeoPath_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetGeoPath_RequestTypeSupport
}

// GetGeoPath_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetGeoPath_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetGeoPath_RequestPublisher creates and returns a new publisher for the
// GetGeoPath_Request
func NewGetGeoPath_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetGeoPath_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetGeoPath_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetGeoPath_RequestPublisher{pub}, nil
}

func (p *GetGeoPath_RequestPublisher) Publish(msg *GetGeoPath_Request) error {
	return p.Publisher.Publish(msg)
}

// GetGeoPath_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetGeoPath_RequestSubscription struct {
	*rclgo.Subscription
}

// GetGeoPath_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetGeoPath_RequestSubscription.
type GetGeoPath_RequestSubscriptionCallback func(msg *GetGeoPath_Request, info *rclgo.MessageInfo, err error)

// NewGetGeoPath_RequestSubscription creates and returns a new subscription for the
// GetGeoPath_Request
func NewGetGeoPath_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetGeoPath_RequestSubscriptionCallback) (*GetGeoPath_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetGeoPath_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetGeoPath_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetGeoPath_RequestSubscription{sub}, nil
}

func (s *GetGeoPath_RequestSubscription) TakeMessage(out *GetGeoPath_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetGeoPath_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetGeoPath_RequestSlice(dst, src []GetGeoPath_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetGeoPath_RequestTypeSupport types.MessageTypeSupport = _GetGeoPath_RequestTypeSupport{}

type _GetGeoPath_RequestTypeSupport struct{}

func (t _GetGeoPath_RequestTypeSupport) New() types.Message {
	return NewGetGeoPath_Request()
}

func (t _GetGeoPath_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__srv__GetGeoPath_Request
	return (unsafe.Pointer)(C.geographic_msgs__srv__GetGeoPath_Request__create())
}

func (t _GetGeoPath_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__srv__GetGeoPath_Request__destroy((*C.geographic_msgs__srv__GetGeoPath_Request)(pointer_to_free))
}

func (t _GetGeoPath_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetGeoPath_Request)
	mem := (*C.geographic_msgs__srv__GetGeoPath_Request)(dst)
	geographic_msgs_msg.GeoPointTypeSupport.AsCStruct(unsafe.Pointer(&mem.start), &m.Start)
	geographic_msgs_msg.GeoPointTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal), &m.Goal)
}

func (t _GetGeoPath_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetGeoPath_Request)
	mem := (*C.geographic_msgs__srv__GetGeoPath_Request)(ros2_message_buffer)
	geographic_msgs_msg.GeoPointTypeSupport.AsGoStruct(&m.Start, unsafe.Pointer(&mem.start))
	geographic_msgs_msg.GeoPointTypeSupport.AsGoStruct(&m.Goal, unsafe.Pointer(&mem.goal))
}

func (t _GetGeoPath_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__srv__GetGeoPath_Request())
}

type CGetGeoPath_Request = C.geographic_msgs__srv__GetGeoPath_Request
type CGetGeoPath_Request__Sequence = C.geographic_msgs__srv__GetGeoPath_Request__Sequence

func GetGeoPath_Request__Sequence_to_Go(goSlice *[]GetGeoPath_Request, cSlice CGetGeoPath_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetGeoPath_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetGeoPath_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetGeoPath_Request__Sequence_to_C(cSlice *CGetGeoPath_Request__Sequence, goSlice []GetGeoPath_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__srv__GetGeoPath_Request)(C.malloc(C.sizeof_struct_geographic_msgs__srv__GetGeoPath_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetGeoPath_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetGeoPath_Request__Array_to_Go(goSlice []GetGeoPath_Request, cSlice []CGetGeoPath_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetGeoPath_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetGeoPath_Request__Array_to_C(cSlice []CGetGeoPath_Request, goSlice []GetGeoPath_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetGeoPath_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
