// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	geographic_msgs_msg "paultio/ros-go/msgs/geographic_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/srv/get_route_plan.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GetRoutePlan_Response", GetRoutePlan_ResponseTypeSupport)
	typemap.RegisterMessage("geographic_msgs/srv/GetRoutePlan_Response", GetRoutePlan_ResponseTypeSupport)
}

type GetRoutePlan_Response struct {
	Success bool `yaml:"success"`// true if the call succeeded
	Status string `yaml:"status"`// more details
	Plan geographic_msgs_msg.RoutePath `yaml:"plan"`// path to follow
}

// NewGetRoutePlan_Response creates a new GetRoutePlan_Response with default values.
func NewGetRoutePlan_Response() *GetRoutePlan_Response {
	self := GetRoutePlan_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetRoutePlan_Response) Clone() *GetRoutePlan_Response {
	c := &GetRoutePlan_Response{}
	c.Success = t.Success
	c.Status = t.Status
	c.Plan = *t.Plan.Clone()
	return c
}

func (t *GetRoutePlan_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetRoutePlan_Response) SetDefaults() {
	t.Success = false
	t.Status = ""
	t.Plan.SetDefaults()
}

func (t *GetRoutePlan_Response) GetTypeSupport() types.MessageTypeSupport {
	return GetRoutePlan_ResponseTypeSupport
}

// GetRoutePlan_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetRoutePlan_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGetRoutePlan_ResponsePublisher creates and returns a new publisher for the
// GetRoutePlan_Response
func NewGetRoutePlan_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetRoutePlan_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetRoutePlan_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetRoutePlan_ResponsePublisher{pub}, nil
}

func (p *GetRoutePlan_ResponsePublisher) Publish(msg *GetRoutePlan_Response) error {
	return p.Publisher.Publish(msg)
}

// GetRoutePlan_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetRoutePlan_ResponseSubscription struct {
	*rclgo.Subscription
}

// GetRoutePlan_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GetRoutePlan_ResponseSubscription.
type GetRoutePlan_ResponseSubscriptionCallback func(msg *GetRoutePlan_Response, info *rclgo.MessageInfo, err error)

// NewGetRoutePlan_ResponseSubscription creates and returns a new subscription for the
// GetRoutePlan_Response
func NewGetRoutePlan_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetRoutePlan_ResponseSubscriptionCallback) (*GetRoutePlan_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetRoutePlan_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetRoutePlan_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetRoutePlan_ResponseSubscription{sub}, nil
}

func (s *GetRoutePlan_ResponseSubscription) TakeMessage(out *GetRoutePlan_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetRoutePlan_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetRoutePlan_ResponseSlice(dst, src []GetRoutePlan_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetRoutePlan_ResponseTypeSupport types.MessageTypeSupport = _GetRoutePlan_ResponseTypeSupport{}

type _GetRoutePlan_ResponseTypeSupport struct{}

func (t _GetRoutePlan_ResponseTypeSupport) New() types.Message {
	return NewGetRoutePlan_Response()
}

func (t _GetRoutePlan_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__srv__GetRoutePlan_Response
	return (unsafe.Pointer)(C.geographic_msgs__srv__GetRoutePlan_Response__create())
}

func (t _GetRoutePlan_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__srv__GetRoutePlan_Response__destroy((*C.geographic_msgs__srv__GetRoutePlan_Response)(pointer_to_free))
}

func (t _GetRoutePlan_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetRoutePlan_Response)
	mem := (*C.geographic_msgs__srv__GetRoutePlan_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status), m.Status)
	geographic_msgs_msg.RoutePathTypeSupport.AsCStruct(unsafe.Pointer(&mem.plan), &m.Plan)
}

func (t _GetRoutePlan_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetRoutePlan_Response)
	mem := (*C.geographic_msgs__srv__GetRoutePlan_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.Status, unsafe.Pointer(&mem.status))
	geographic_msgs_msg.RoutePathTypeSupport.AsGoStruct(&m.Plan, unsafe.Pointer(&mem.plan))
}

func (t _GetRoutePlan_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__srv__GetRoutePlan_Response())
}

type CGetRoutePlan_Response = C.geographic_msgs__srv__GetRoutePlan_Response
type CGetRoutePlan_Response__Sequence = C.geographic_msgs__srv__GetRoutePlan_Response__Sequence

func GetRoutePlan_Response__Sequence_to_Go(goSlice *[]GetRoutePlan_Response, cSlice CGetRoutePlan_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetRoutePlan_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetRoutePlan_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetRoutePlan_Response__Sequence_to_C(cSlice *CGetRoutePlan_Response__Sequence, goSlice []GetRoutePlan_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__srv__GetRoutePlan_Response)(C.malloc(C.sizeof_struct_geographic_msgs__srv__GetRoutePlan_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetRoutePlan_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetRoutePlan_Response__Array_to_Go(goSlice []GetRoutePlan_Response, cSlice []CGetRoutePlan_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetRoutePlan_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetRoutePlan_Response__Array_to_C(cSlice []CGetRoutePlan_Response, goSlice []GetRoutePlan_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetRoutePlan_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
