// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geographic_msgs_msg "paultio/ros-go/msgs/geographic_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/srv/update_geographic_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/UpdateGeographicMap_Request", UpdateGeographicMap_RequestTypeSupport)
	typemap.RegisterMessage("geographic_msgs/srv/UpdateGeographicMap_Request", UpdateGeographicMap_RequestTypeSupport)
}

type UpdateGeographicMap_Request struct {
	Updates geographic_msgs_msg.GeographicMapChanges `yaml:"updates"`// Changes to geographic map.
}

// NewUpdateGeographicMap_Request creates a new UpdateGeographicMap_Request with default values.
func NewUpdateGeographicMap_Request() *UpdateGeographicMap_Request {
	self := UpdateGeographicMap_Request{}
	self.SetDefaults()
	return &self
}

func (t *UpdateGeographicMap_Request) Clone() *UpdateGeographicMap_Request {
	c := &UpdateGeographicMap_Request{}
	c.Updates = *t.Updates.Clone()
	return c
}

func (t *UpdateGeographicMap_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *UpdateGeographicMap_Request) SetDefaults() {
	t.Updates.SetDefaults()
}

func (t *UpdateGeographicMap_Request) GetTypeSupport() types.MessageTypeSupport {
	return UpdateGeographicMap_RequestTypeSupport
}

// UpdateGeographicMap_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type UpdateGeographicMap_RequestPublisher struct {
	*rclgo.Publisher
}

// NewUpdateGeographicMap_RequestPublisher creates and returns a new publisher for the
// UpdateGeographicMap_Request
func NewUpdateGeographicMap_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*UpdateGeographicMap_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, UpdateGeographicMap_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &UpdateGeographicMap_RequestPublisher{pub}, nil
}

func (p *UpdateGeographicMap_RequestPublisher) Publish(msg *UpdateGeographicMap_Request) error {
	return p.Publisher.Publish(msg)
}

// UpdateGeographicMap_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type UpdateGeographicMap_RequestSubscription struct {
	*rclgo.Subscription
}

// UpdateGeographicMap_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a UpdateGeographicMap_RequestSubscription.
type UpdateGeographicMap_RequestSubscriptionCallback func(msg *UpdateGeographicMap_Request, info *rclgo.MessageInfo, err error)

// NewUpdateGeographicMap_RequestSubscription creates and returns a new subscription for the
// UpdateGeographicMap_Request
func NewUpdateGeographicMap_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback UpdateGeographicMap_RequestSubscriptionCallback) (*UpdateGeographicMap_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg UpdateGeographicMap_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, UpdateGeographicMap_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &UpdateGeographicMap_RequestSubscription{sub}, nil
}

func (s *UpdateGeographicMap_RequestSubscription) TakeMessage(out *UpdateGeographicMap_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneUpdateGeographicMap_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneUpdateGeographicMap_RequestSlice(dst, src []UpdateGeographicMap_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var UpdateGeographicMap_RequestTypeSupport types.MessageTypeSupport = _UpdateGeographicMap_RequestTypeSupport{}

type _UpdateGeographicMap_RequestTypeSupport struct{}

func (t _UpdateGeographicMap_RequestTypeSupport) New() types.Message {
	return NewUpdateGeographicMap_Request()
}

func (t _UpdateGeographicMap_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__srv__UpdateGeographicMap_Request
	return (unsafe.Pointer)(C.geographic_msgs__srv__UpdateGeographicMap_Request__create())
}

func (t _UpdateGeographicMap_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__srv__UpdateGeographicMap_Request__destroy((*C.geographic_msgs__srv__UpdateGeographicMap_Request)(pointer_to_free))
}

func (t _UpdateGeographicMap_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*UpdateGeographicMap_Request)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Request)(dst)
	geographic_msgs_msg.GeographicMapChangesTypeSupport.AsCStruct(unsafe.Pointer(&mem.updates), &m.Updates)
}

func (t _UpdateGeographicMap_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*UpdateGeographicMap_Request)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Request)(ros2_message_buffer)
	geographic_msgs_msg.GeographicMapChangesTypeSupport.AsGoStruct(&m.Updates, unsafe.Pointer(&mem.updates))
}

func (t _UpdateGeographicMap_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__srv__UpdateGeographicMap_Request())
}

type CUpdateGeographicMap_Request = C.geographic_msgs__srv__UpdateGeographicMap_Request
type CUpdateGeographicMap_Request__Sequence = C.geographic_msgs__srv__UpdateGeographicMap_Request__Sequence

func UpdateGeographicMap_Request__Sequence_to_Go(goSlice *[]UpdateGeographicMap_Request, cSlice CUpdateGeographicMap_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]UpdateGeographicMap_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		UpdateGeographicMap_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func UpdateGeographicMap_Request__Sequence_to_C(cSlice *CUpdateGeographicMap_Request__Sequence, goSlice []UpdateGeographicMap_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__srv__UpdateGeographicMap_Request)(C.malloc(C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		UpdateGeographicMap_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func UpdateGeographicMap_Request__Array_to_Go(goSlice []UpdateGeographicMap_Request, cSlice []CUpdateGeographicMap_Request) {
	for i := 0; i < len(cSlice); i++ {
		UpdateGeographicMap_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func UpdateGeographicMap_Request__Array_to_C(cSlice []CUpdateGeographicMap_Request, goSlice []UpdateGeographicMap_Request) {
	for i := 0; i < len(goSlice); i++ {
		UpdateGeographicMap_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
