// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <geographic_msgs/srv/update_geographic_map.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("geographic_msgs/UpdateGeographicMap", UpdateGeographicMapTypeSupport)
	typemap.RegisterService("geographic_msgs/srv/UpdateGeographicMap", UpdateGeographicMapTypeSupport)
}

type _UpdateGeographicMapTypeSupport struct {}

func (s _UpdateGeographicMapTypeSupport) Request() types.MessageTypeSupport {
	return UpdateGeographicMap_RequestTypeSupport
}

func (s _UpdateGeographicMapTypeSupport) Response() types.MessageTypeSupport {
	return UpdateGeographicMap_ResponseTypeSupport
}

func (s _UpdateGeographicMapTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__geographic_msgs__srv__UpdateGeographicMap())
}

// Modifying this variable is undefined behavior.
var UpdateGeographicMapTypeSupport types.ServiceTypeSupport = _UpdateGeographicMapTypeSupport{}

// UpdateGeographicMapClient wraps rclgo.Client to provide type safe helper
// functions
type UpdateGeographicMapClient struct {
	*rclgo.Client
}

// NewUpdateGeographicMapClient creates and returns a new client for the
// UpdateGeographicMap
func NewUpdateGeographicMapClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*UpdateGeographicMapClient, error) {
	client, err := node.NewClient(serviceName, UpdateGeographicMapTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &UpdateGeographicMapClient{client}, nil
}

func (s *UpdateGeographicMapClient) Send(ctx context.Context, req *UpdateGeographicMap_Request) (*UpdateGeographicMap_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*UpdateGeographicMap_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type UpdateGeographicMapServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s UpdateGeographicMapServiceResponseSender) SendResponse(resp *UpdateGeographicMap_Response) error {
	return s.sender.SendResponse(resp)
}

type UpdateGeographicMapServiceRequestHandler func(*rclgo.ServiceInfo, *UpdateGeographicMap_Request, UpdateGeographicMapServiceResponseSender)

// UpdateGeographicMapService wraps rclgo.Service to provide type safe helper
// functions
type UpdateGeographicMapService struct {
	*rclgo.Service
}

// NewUpdateGeographicMapService creates and returns a new service for the
// UpdateGeographicMap
func NewUpdateGeographicMapService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler UpdateGeographicMapServiceRequestHandler) (*UpdateGeographicMapService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*UpdateGeographicMap_Request)
		responseSender := UpdateGeographicMapServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, UpdateGeographicMapTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &UpdateGeographicMapService{service}, nil
}