// Code generated by rclgo-gen. DO NOT EDIT.

package geographic_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/srv/update_geographic_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/UpdateGeographicMap_Response", UpdateGeographicMap_ResponseTypeSupport)
	typemap.RegisterMessage("geographic_msgs/srv/UpdateGeographicMap_Response", UpdateGeographicMap_ResponseTypeSupport)
}

type UpdateGeographicMap_Response struct {
	Success bool `yaml:"success"`// true if the call succeeded
	Status string `yaml:"status"`// more details
}

// NewUpdateGeographicMap_Response creates a new UpdateGeographicMap_Response with default values.
func NewUpdateGeographicMap_Response() *UpdateGeographicMap_Response {
	self := UpdateGeographicMap_Response{}
	self.SetDefaults()
	return &self
}

func (t *UpdateGeographicMap_Response) Clone() *UpdateGeographicMap_Response {
	c := &UpdateGeographicMap_Response{}
	c.Success = t.Success
	c.Status = t.Status
	return c
}

func (t *UpdateGeographicMap_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *UpdateGeographicMap_Response) SetDefaults() {
	t.Success = false
	t.Status = ""
}

func (t *UpdateGeographicMap_Response) GetTypeSupport() types.MessageTypeSupport {
	return UpdateGeographicMap_ResponseTypeSupport
}

// UpdateGeographicMap_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type UpdateGeographicMap_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewUpdateGeographicMap_ResponsePublisher creates and returns a new publisher for the
// UpdateGeographicMap_Response
func NewUpdateGeographicMap_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*UpdateGeographicMap_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, UpdateGeographicMap_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &UpdateGeographicMap_ResponsePublisher{pub}, nil
}

func (p *UpdateGeographicMap_ResponsePublisher) Publish(msg *UpdateGeographicMap_Response) error {
	return p.Publisher.Publish(msg)
}

// UpdateGeographicMap_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type UpdateGeographicMap_ResponseSubscription struct {
	*rclgo.Subscription
}

// UpdateGeographicMap_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a UpdateGeographicMap_ResponseSubscription.
type UpdateGeographicMap_ResponseSubscriptionCallback func(msg *UpdateGeographicMap_Response, info *rclgo.MessageInfo, err error)

// NewUpdateGeographicMap_ResponseSubscription creates and returns a new subscription for the
// UpdateGeographicMap_Response
func NewUpdateGeographicMap_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback UpdateGeographicMap_ResponseSubscriptionCallback) (*UpdateGeographicMap_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg UpdateGeographicMap_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, UpdateGeographicMap_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &UpdateGeographicMap_ResponseSubscription{sub}, nil
}

func (s *UpdateGeographicMap_ResponseSubscription) TakeMessage(out *UpdateGeographicMap_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneUpdateGeographicMap_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneUpdateGeographicMap_ResponseSlice(dst, src []UpdateGeographicMap_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var UpdateGeographicMap_ResponseTypeSupport types.MessageTypeSupport = _UpdateGeographicMap_ResponseTypeSupport{}

type _UpdateGeographicMap_ResponseTypeSupport struct{}

func (t _UpdateGeographicMap_ResponseTypeSupport) New() types.Message {
	return NewUpdateGeographicMap_Response()
}

func (t _UpdateGeographicMap_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__srv__UpdateGeographicMap_Response
	return (unsafe.Pointer)(C.geographic_msgs__srv__UpdateGeographicMap_Response__create())
}

func (t _UpdateGeographicMap_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__srv__UpdateGeographicMap_Response__destroy((*C.geographic_msgs__srv__UpdateGeographicMap_Response)(pointer_to_free))
}

func (t _UpdateGeographicMap_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*UpdateGeographicMap_Response)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status), m.Status)
}

func (t _UpdateGeographicMap_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*UpdateGeographicMap_Response)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.Status, unsafe.Pointer(&mem.status))
}

func (t _UpdateGeographicMap_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__srv__UpdateGeographicMap_Response())
}

type CUpdateGeographicMap_Response = C.geographic_msgs__srv__UpdateGeographicMap_Response
type CUpdateGeographicMap_Response__Sequence = C.geographic_msgs__srv__UpdateGeographicMap_Response__Sequence

func UpdateGeographicMap_Response__Sequence_to_Go(goSlice *[]UpdateGeographicMap_Response, cSlice CUpdateGeographicMap_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]UpdateGeographicMap_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		UpdateGeographicMap_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func UpdateGeographicMap_Response__Sequence_to_C(cSlice *CUpdateGeographicMap_Response__Sequence, goSlice []UpdateGeographicMap_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__srv__UpdateGeographicMap_Response)(C.malloc(C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		UpdateGeographicMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func UpdateGeographicMap_Response__Array_to_Go(goSlice []UpdateGeographicMap_Response, cSlice []CUpdateGeographicMap_Response) {
	for i := 0; i < len(cSlice); i++ {
		UpdateGeographicMap_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func UpdateGeographicMap_Response__Array_to_C(cSlice []CUpdateGeographicMap_Response, goSlice []UpdateGeographicMap_Response) {
	for i := 0; i < len(goSlice); i++ {
		UpdateGeographicMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
