// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/get_rate.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/GetRate_Request", GetRate_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/GetRate_Request", GetRate_RequestTypeSupport)
}

type GetRate_Request struct {
}

// NewGetRate_Request creates a new GetRate_Request with default values.
func NewGetRate_Request() *GetRate_Request {
	self := GetRate_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetRate_Request) Clone() *GetRate_Request {
	c := &GetRate_Request{}
	return c
}

func (t *GetRate_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetRate_Request) SetDefaults() {
}

func (t *GetRate_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetRate_RequestTypeSupport
}

// GetRate_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetRate_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetRate_RequestPublisher creates and returns a new publisher for the
// GetRate_Request
func NewGetRate_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetRate_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetRate_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetRate_RequestPublisher{pub}, nil
}

func (p *GetRate_RequestPublisher) Publish(msg *GetRate_Request) error {
	return p.Publisher.Publish(msg)
}

// GetRate_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetRate_RequestSubscription struct {
	*rclgo.Subscription
}

// GetRate_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetRate_RequestSubscription.
type GetRate_RequestSubscriptionCallback func(msg *GetRate_Request, info *rclgo.MessageInfo, err error)

// NewGetRate_RequestSubscription creates and returns a new subscription for the
// GetRate_Request
func NewGetRate_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetRate_RequestSubscriptionCallback) (*GetRate_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetRate_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetRate_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetRate_RequestSubscription{sub}, nil
}

func (s *GetRate_RequestSubscription) TakeMessage(out *GetRate_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetRate_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetRate_RequestSlice(dst, src []GetRate_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetRate_RequestTypeSupport types.MessageTypeSupport = _GetRate_RequestTypeSupport{}

type _GetRate_RequestTypeSupport struct{}

func (t _GetRate_RequestTypeSupport) New() types.Message {
	return NewGetRate_Request()
}

func (t _GetRate_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__GetRate_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__GetRate_Request__create())
}

func (t _GetRate_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__GetRate_Request__destroy((*C.rosbag2_interfaces__srv__GetRate_Request)(pointer_to_free))
}

func (t _GetRate_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetRate_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetRate_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__GetRate_Request())
}

type CGetRate_Request = C.rosbag2_interfaces__srv__GetRate_Request
type CGetRate_Request__Sequence = C.rosbag2_interfaces__srv__GetRate_Request__Sequence

func GetRate_Request__Sequence_to_Go(goSlice *[]GetRate_Request, cSlice CGetRate_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetRate_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetRate_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetRate_Request__Sequence_to_C(cSlice *CGetRate_Request__Sequence, goSlice []GetRate_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__GetRate_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__GetRate_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetRate_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetRate_Request__Array_to_Go(goSlice []GetRate_Request, cSlice []CGetRate_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetRate_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetRate_Request__Array_to_C(cSlice []CGetRate_Request, goSlice []GetRate_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetRate_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
