// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/get_rate.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/GetRate_Response", GetRate_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/GetRate_Response", GetRate_ResponseTypeSupport)
}

type GetRate_Response struct {
	Rate float64 `yaml:"rate"`
}

// NewGetRate_Response creates a new GetRate_Response with default values.
func NewGetRate_Response() *GetRate_Response {
	self := GetRate_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetRate_Response) Clone() *GetRate_Response {
	c := &GetRate_Response{}
	c.Rate = t.Rate
	return c
}

func (t *GetRate_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetRate_Response) SetDefaults() {
	t.Rate = 0
}

func (t *GetRate_Response) GetTypeSupport() types.MessageTypeSupport {
	return GetRate_ResponseTypeSupport
}

// GetRate_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetRate_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGetRate_ResponsePublisher creates and returns a new publisher for the
// GetRate_Response
func NewGetRate_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetRate_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetRate_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetRate_ResponsePublisher{pub}, nil
}

func (p *GetRate_ResponsePublisher) Publish(msg *GetRate_Response) error {
	return p.Publisher.Publish(msg)
}

// GetRate_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetRate_ResponseSubscription struct {
	*rclgo.Subscription
}

// GetRate_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GetRate_ResponseSubscription.
type GetRate_ResponseSubscriptionCallback func(msg *GetRate_Response, info *rclgo.MessageInfo, err error)

// NewGetRate_ResponseSubscription creates and returns a new subscription for the
// GetRate_Response
func NewGetRate_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetRate_ResponseSubscriptionCallback) (*GetRate_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetRate_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetRate_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetRate_ResponseSubscription{sub}, nil
}

func (s *GetRate_ResponseSubscription) TakeMessage(out *GetRate_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetRate_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetRate_ResponseSlice(dst, src []GetRate_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetRate_ResponseTypeSupport types.MessageTypeSupport = _GetRate_ResponseTypeSupport{}

type _GetRate_ResponseTypeSupport struct{}

func (t _GetRate_ResponseTypeSupport) New() types.Message {
	return NewGetRate_Response()
}

func (t _GetRate_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__GetRate_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__GetRate_Response__create())
}

func (t _GetRate_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__GetRate_Response__destroy((*C.rosbag2_interfaces__srv__GetRate_Response)(pointer_to_free))
}

func (t _GetRate_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetRate_Response)
	mem := (*C.rosbag2_interfaces__srv__GetRate_Response)(dst)
	mem.rate = C.double(m.Rate)
}

func (t _GetRate_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetRate_Response)
	mem := (*C.rosbag2_interfaces__srv__GetRate_Response)(ros2_message_buffer)
	m.Rate = float64(mem.rate)
}

func (t _GetRate_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__GetRate_Response())
}

type CGetRate_Response = C.rosbag2_interfaces__srv__GetRate_Response
type CGetRate_Response__Sequence = C.rosbag2_interfaces__srv__GetRate_Response__Sequence

func GetRate_Response__Sequence_to_Go(goSlice *[]GetRate_Response, cSlice CGetRate_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetRate_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetRate_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetRate_Response__Sequence_to_C(cSlice *CGetRate_Response__Sequence, goSlice []GetRate_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__GetRate_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__GetRate_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetRate_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetRate_Response__Array_to_Go(goSlice []GetRate_Response, cSlice []CGetRate_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetRate_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetRate_Response__Array_to_C(cSlice []CGetRate_Response, goSlice []GetRate_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetRate_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
