// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/is_paused.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/IsPaused", IsPausedTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/IsPaused", IsPausedTypeSupport)
}

type _IsPausedTypeSupport struct {}

func (s _IsPausedTypeSupport) Request() types.MessageTypeSupport {
	return IsPaused_RequestTypeSupport
}

func (s _IsPausedTypeSupport) Response() types.MessageTypeSupport {
	return IsPaused_ResponseTypeSupport
}

func (s _IsPausedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__IsPaused())
}

// Modifying this variable is undefined behavior.
var IsPausedTypeSupport types.ServiceTypeSupport = _IsPausedTypeSupport{}

// IsPausedClient wraps rclgo.Client to provide type safe helper
// functions
type IsPausedClient struct {
	*rclgo.Client
}

// NewIsPausedClient creates and returns a new client for the
// IsPaused
func NewIsPausedClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*IsPausedClient, error) {
	client, err := node.NewClient(serviceName, IsPausedTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IsPausedClient{client}, nil
}

func (s *IsPausedClient) Send(ctx context.Context, req *IsPaused_Request) (*IsPaused_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*IsPaused_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type IsPausedServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s IsPausedServiceResponseSender) SendResponse(resp *IsPaused_Response) error {
	return s.sender.SendResponse(resp)
}

type IsPausedServiceRequestHandler func(*rclgo.ServiceInfo, *IsPaused_Request, IsPausedServiceResponseSender)

// IsPausedService wraps rclgo.Service to provide type safe helper
// functions
type IsPausedService struct {
	*rclgo.Service
}

// NewIsPausedService creates and returns a new service for the
// IsPaused
func NewIsPausedService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler IsPausedServiceRequestHandler) (*IsPausedService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*IsPaused_Request)
		responseSender := IsPausedServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, IsPausedTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &IsPausedService{service}, nil
}