// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/is_paused.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/IsPaused_Response", IsPaused_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/IsPaused_Response", IsPaused_ResponseTypeSupport)
}

type IsPaused_Response struct {
	Paused bool `yaml:"paused"`
}

// NewIsPaused_Response creates a new IsPaused_Response with default values.
func NewIsPaused_Response() *IsPaused_Response {
	self := IsPaused_Response{}
	self.SetDefaults()
	return &self
}

func (t *IsPaused_Response) Clone() *IsPaused_Response {
	c := &IsPaused_Response{}
	c.Paused = t.Paused
	return c
}

func (t *IsPaused_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *IsPaused_Response) SetDefaults() {
	t.Paused = false
}

func (t *IsPaused_Response) GetTypeSupport() types.MessageTypeSupport {
	return IsPaused_ResponseTypeSupport
}

// IsPaused_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type IsPaused_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewIsPaused_ResponsePublisher creates and returns a new publisher for the
// IsPaused_Response
func NewIsPaused_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*IsPaused_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, IsPaused_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IsPaused_ResponsePublisher{pub}, nil
}

func (p *IsPaused_ResponsePublisher) Publish(msg *IsPaused_Response) error {
	return p.Publisher.Publish(msg)
}

// IsPaused_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type IsPaused_ResponseSubscription struct {
	*rclgo.Subscription
}

// IsPaused_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a IsPaused_ResponseSubscription.
type IsPaused_ResponseSubscriptionCallback func(msg *IsPaused_Response, info *rclgo.MessageInfo, err error)

// NewIsPaused_ResponseSubscription creates and returns a new subscription for the
// IsPaused_Response
func NewIsPaused_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback IsPaused_ResponseSubscriptionCallback) (*IsPaused_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg IsPaused_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, IsPaused_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &IsPaused_ResponseSubscription{sub}, nil
}

func (s *IsPaused_ResponseSubscription) TakeMessage(out *IsPaused_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneIsPaused_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIsPaused_ResponseSlice(dst, src []IsPaused_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IsPaused_ResponseTypeSupport types.MessageTypeSupport = _IsPaused_ResponseTypeSupport{}

type _IsPaused_ResponseTypeSupport struct{}

func (t _IsPaused_ResponseTypeSupport) New() types.Message {
	return NewIsPaused_Response()
}

func (t _IsPaused_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__IsPaused_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__IsPaused_Response__create())
}

func (t _IsPaused_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__IsPaused_Response__destroy((*C.rosbag2_interfaces__srv__IsPaused_Response)(pointer_to_free))
}

func (t _IsPaused_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*IsPaused_Response)
	mem := (*C.rosbag2_interfaces__srv__IsPaused_Response)(dst)
	mem.paused = C.bool(m.Paused)
}

func (t _IsPaused_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*IsPaused_Response)
	mem := (*C.rosbag2_interfaces__srv__IsPaused_Response)(ros2_message_buffer)
	m.Paused = bool(mem.paused)
}

func (t _IsPaused_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__IsPaused_Response())
}

type CIsPaused_Response = C.rosbag2_interfaces__srv__IsPaused_Response
type CIsPaused_Response__Sequence = C.rosbag2_interfaces__srv__IsPaused_Response__Sequence

func IsPaused_Response__Sequence_to_Go(goSlice *[]IsPaused_Response, cSlice CIsPaused_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]IsPaused_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		IsPaused_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func IsPaused_Response__Sequence_to_C(cSlice *CIsPaused_Response__Sequence, goSlice []IsPaused_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__IsPaused_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__IsPaused_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		IsPaused_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func IsPaused_Response__Array_to_Go(goSlice []IsPaused_Response, cSlice []CIsPaused_Response) {
	for i := 0; i < len(cSlice); i++ {
		IsPaused_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func IsPaused_Response__Array_to_C(cSlice []CIsPaused_Response, goSlice []IsPaused_Response) {
	for i := 0; i < len(goSlice); i++ {
		IsPaused_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
