// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/play_next.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/PlayNext", PlayNextTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/PlayNext", PlayNextTypeSupport)
}

type _PlayNextTypeSupport struct {}

func (s _PlayNextTypeSupport) Request() types.MessageTypeSupport {
	return PlayNext_RequestTypeSupport
}

func (s _PlayNextTypeSupport) Response() types.MessageTypeSupport {
	return PlayNext_ResponseTypeSupport
}

func (s _PlayNextTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__PlayNext())
}

// Modifying this variable is undefined behavior.
var PlayNextTypeSupport types.ServiceTypeSupport = _PlayNextTypeSupport{}

// PlayNextClient wraps rclgo.Client to provide type safe helper
// functions
type PlayNextClient struct {
	*rclgo.Client
}

// NewPlayNextClient creates and returns a new client for the
// PlayNext
func NewPlayNextClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*PlayNextClient, error) {
	client, err := node.NewClient(serviceName, PlayNextTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PlayNextClient{client}, nil
}

func (s *PlayNextClient) Send(ctx context.Context, req *PlayNext_Request) (*PlayNext_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*PlayNext_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type PlayNextServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s PlayNextServiceResponseSender) SendResponse(resp *PlayNext_Response) error {
	return s.sender.SendResponse(resp)
}

type PlayNextServiceRequestHandler func(*rclgo.ServiceInfo, *PlayNext_Request, PlayNextServiceResponseSender)

// PlayNextService wraps rclgo.Service to provide type safe helper
// functions
type PlayNextService struct {
	*rclgo.Service
}

// NewPlayNextService creates and returns a new service for the
// PlayNext
func NewPlayNextService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler PlayNextServiceRequestHandler) (*PlayNextService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*PlayNext_Request)
		responseSender := PlayNextServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, PlayNextTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &PlayNextService{service}, nil
}