// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/play_next.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/PlayNext_Response", PlayNext_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/PlayNext_Response", PlayNext_ResponseTypeSupport)
}

type PlayNext_Response struct {
	Success bool `yaml:"success"`// can only play-next while playback is paused
}

// NewPlayNext_Response creates a new PlayNext_Response with default values.
func NewPlayNext_Response() *PlayNext_Response {
	self := PlayNext_Response{}
	self.SetDefaults()
	return &self
}

func (t *PlayNext_Response) Clone() *PlayNext_Response {
	c := &PlayNext_Response{}
	c.Success = t.Success
	return c
}

func (t *PlayNext_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *PlayNext_Response) SetDefaults() {
	t.Success = false
}

func (t *PlayNext_Response) GetTypeSupport() types.MessageTypeSupport {
	return PlayNext_ResponseTypeSupport
}

// PlayNext_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type PlayNext_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewPlayNext_ResponsePublisher creates and returns a new publisher for the
// PlayNext_Response
func NewPlayNext_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*PlayNext_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, PlayNext_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PlayNext_ResponsePublisher{pub}, nil
}

func (p *PlayNext_ResponsePublisher) Publish(msg *PlayNext_Response) error {
	return p.Publisher.Publish(msg)
}

// PlayNext_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type PlayNext_ResponseSubscription struct {
	*rclgo.Subscription
}

// PlayNext_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a PlayNext_ResponseSubscription.
type PlayNext_ResponseSubscriptionCallback func(msg *PlayNext_Response, info *rclgo.MessageInfo, err error)

// NewPlayNext_ResponseSubscription creates and returns a new subscription for the
// PlayNext_Response
func NewPlayNext_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback PlayNext_ResponseSubscriptionCallback) (*PlayNext_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg PlayNext_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, PlayNext_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &PlayNext_ResponseSubscription{sub}, nil
}

func (s *PlayNext_ResponseSubscription) TakeMessage(out *PlayNext_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePlayNext_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePlayNext_ResponseSlice(dst, src []PlayNext_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var PlayNext_ResponseTypeSupport types.MessageTypeSupport = _PlayNext_ResponseTypeSupport{}

type _PlayNext_ResponseTypeSupport struct{}

func (t _PlayNext_ResponseTypeSupport) New() types.Message {
	return NewPlayNext_Response()
}

func (t _PlayNext_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__PlayNext_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__PlayNext_Response__create())
}

func (t _PlayNext_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__PlayNext_Response__destroy((*C.rosbag2_interfaces__srv__PlayNext_Response)(pointer_to_free))
}

func (t _PlayNext_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*PlayNext_Response)
	mem := (*C.rosbag2_interfaces__srv__PlayNext_Response)(dst)
	mem.success = C.bool(m.Success)
}

func (t _PlayNext_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*PlayNext_Response)
	mem := (*C.rosbag2_interfaces__srv__PlayNext_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
}

func (t _PlayNext_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__PlayNext_Response())
}

type CPlayNext_Response = C.rosbag2_interfaces__srv__PlayNext_Response
type CPlayNext_Response__Sequence = C.rosbag2_interfaces__srv__PlayNext_Response__Sequence

func PlayNext_Response__Sequence_to_Go(goSlice *[]PlayNext_Response, cSlice CPlayNext_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]PlayNext_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		PlayNext_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func PlayNext_Response__Sequence_to_C(cSlice *CPlayNext_Response__Sequence, goSlice []PlayNext_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__PlayNext_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__PlayNext_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		PlayNext_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func PlayNext_Response__Array_to_Go(goSlice []PlayNext_Response, cSlice []CPlayNext_Response) {
	for i := 0; i < len(cSlice); i++ {
		PlayNext_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func PlayNext_Response__Array_to_C(cSlice []CPlayNext_Response, goSlice []PlayNext_Response) {
	for i := 0; i < len(goSlice); i++ {
		PlayNext_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
