// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/resume.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Resume_Request", Resume_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Resume_Request", Resume_RequestTypeSupport)
}

type Resume_Request struct {
}

// NewResume_Request creates a new Resume_Request with default values.
func NewResume_Request() *Resume_Request {
	self := Resume_Request{}
	self.SetDefaults()
	return &self
}

func (t *Resume_Request) Clone() *Resume_Request {
	c := &Resume_Request{}
	return c
}

func (t *Resume_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Resume_Request) SetDefaults() {
}

func (t *Resume_Request) GetTypeSupport() types.MessageTypeSupport {
	return Resume_RequestTypeSupport
}

// Resume_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Resume_RequestPublisher struct {
	*rclgo.Publisher
}

// NewResume_RequestPublisher creates and returns a new publisher for the
// Resume_Request
func NewResume_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Resume_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Resume_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Resume_RequestPublisher{pub}, nil
}

func (p *Resume_RequestPublisher) Publish(msg *Resume_Request) error {
	return p.Publisher.Publish(msg)
}

// Resume_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Resume_RequestSubscription struct {
	*rclgo.Subscription
}

// Resume_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a Resume_RequestSubscription.
type Resume_RequestSubscriptionCallback func(msg *Resume_Request, info *rclgo.MessageInfo, err error)

// NewResume_RequestSubscription creates and returns a new subscription for the
// Resume_Request
func NewResume_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Resume_RequestSubscriptionCallback) (*Resume_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Resume_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Resume_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Resume_RequestSubscription{sub}, nil
}

func (s *Resume_RequestSubscription) TakeMessage(out *Resume_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneResume_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResume_RequestSlice(dst, src []Resume_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Resume_RequestTypeSupport types.MessageTypeSupport = _Resume_RequestTypeSupport{}

type _Resume_RequestTypeSupport struct{}

func (t _Resume_RequestTypeSupport) New() types.Message {
	return NewResume_Request()
}

func (t _Resume_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Resume_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Resume_Request__create())
}

func (t _Resume_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Resume_Request__destroy((*C.rosbag2_interfaces__srv__Resume_Request)(pointer_to_free))
}

func (t _Resume_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _Resume_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _Resume_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Resume_Request())
}

type CResume_Request = C.rosbag2_interfaces__srv__Resume_Request
type CResume_Request__Sequence = C.rosbag2_interfaces__srv__Resume_Request__Sequence

func Resume_Request__Sequence_to_Go(goSlice *[]Resume_Request, cSlice CResume_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Resume_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Resume_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Resume_Request__Sequence_to_C(cSlice *CResume_Request__Sequence, goSlice []Resume_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Resume_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Resume_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Resume_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Resume_Request__Array_to_Go(goSlice []Resume_Request, cSlice []CResume_Request) {
	for i := 0; i < len(cSlice); i++ {
		Resume_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Resume_Request__Array_to_C(cSlice []CResume_Request, goSlice []Resume_Request) {
	for i := 0; i < len(goSlice); i++ {
		Resume_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
