// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/resume.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Resume_Response", Resume_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Resume_Response", Resume_ResponseTypeSupport)
}

type Resume_Response struct {
}

// NewResume_Response creates a new Resume_Response with default values.
func NewResume_Response() *Resume_Response {
	self := Resume_Response{}
	self.SetDefaults()
	return &self
}

func (t *Resume_Response) Clone() *Resume_Response {
	c := &Resume_Response{}
	return c
}

func (t *Resume_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Resume_Response) SetDefaults() {
}

func (t *Resume_Response) GetTypeSupport() types.MessageTypeSupport {
	return Resume_ResponseTypeSupport
}

// Resume_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Resume_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewResume_ResponsePublisher creates and returns a new publisher for the
// Resume_Response
func NewResume_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Resume_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, Resume_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Resume_ResponsePublisher{pub}, nil
}

func (p *Resume_ResponsePublisher) Publish(msg *Resume_Response) error {
	return p.Publisher.Publish(msg)
}

// Resume_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Resume_ResponseSubscription struct {
	*rclgo.Subscription
}

// Resume_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Resume_ResponseSubscription.
type Resume_ResponseSubscriptionCallback func(msg *Resume_Response, info *rclgo.MessageInfo, err error)

// NewResume_ResponseSubscription creates and returns a new subscription for the
// Resume_Response
func NewResume_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Resume_ResponseSubscriptionCallback) (*Resume_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Resume_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Resume_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Resume_ResponseSubscription{sub}, nil
}

func (s *Resume_ResponseSubscription) TakeMessage(out *Resume_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneResume_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResume_ResponseSlice(dst, src []Resume_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Resume_ResponseTypeSupport types.MessageTypeSupport = _Resume_ResponseTypeSupport{}

type _Resume_ResponseTypeSupport struct{}

func (t _Resume_ResponseTypeSupport) New() types.Message {
	return NewResume_Response()
}

func (t _Resume_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Resume_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Resume_Response__create())
}

func (t _Resume_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Resume_Response__destroy((*C.rosbag2_interfaces__srv__Resume_Response)(pointer_to_free))
}

func (t _Resume_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _Resume_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _Resume_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Resume_Response())
}

type CResume_Response = C.rosbag2_interfaces__srv__Resume_Response
type CResume_Response__Sequence = C.rosbag2_interfaces__srv__Resume_Response__Sequence

func Resume_Response__Sequence_to_Go(goSlice *[]Resume_Response, cSlice CResume_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Resume_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Resume_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Resume_Response__Sequence_to_C(cSlice *CResume_Response__Sequence, goSlice []Resume_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Resume_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Resume_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Resume_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Resume_Response__Array_to_Go(goSlice []Resume_Response, cSlice []CResume_Response) {
	for i := 0; i < len(cSlice); i++ {
		Resume_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Resume_Response__Array_to_C(cSlice []CResume_Response, goSlice []Resume_Response) {
	for i := 0; i < len(goSlice); i++ {
		Resume_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
