// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "paultio/ros-go/msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/seek.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Seek_Request", Seek_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Seek_Request", Seek_RequestTypeSupport)
}

type Seek_Request struct {
	Time builtin_interfaces_msg.Time `yaml:"time"`
}

// NewSeek_Request creates a new Seek_Request with default values.
func NewSeek_Request() *Seek_Request {
	self := Seek_Request{}
	self.SetDefaults()
	return &self
}

func (t *Seek_Request) Clone() *Seek_Request {
	c := &Seek_Request{}
	c.Time = *t.Time.Clone()
	return c
}

func (t *Seek_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Seek_Request) SetDefaults() {
	t.Time.SetDefaults()
}

func (t *Seek_Request) GetTypeSupport() types.MessageTypeSupport {
	return Seek_RequestTypeSupport
}

// Seek_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Seek_RequestPublisher struct {
	*rclgo.Publisher
}

// NewSeek_RequestPublisher creates and returns a new publisher for the
// Seek_Request
func NewSeek_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Seek_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Seek_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Seek_RequestPublisher{pub}, nil
}

func (p *Seek_RequestPublisher) Publish(msg *Seek_Request) error {
	return p.Publisher.Publish(msg)
}

// Seek_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Seek_RequestSubscription struct {
	*rclgo.Subscription
}

// Seek_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a Seek_RequestSubscription.
type Seek_RequestSubscriptionCallback func(msg *Seek_Request, info *rclgo.MessageInfo, err error)

// NewSeek_RequestSubscription creates and returns a new subscription for the
// Seek_Request
func NewSeek_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Seek_RequestSubscriptionCallback) (*Seek_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Seek_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Seek_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Seek_RequestSubscription{sub}, nil
}

func (s *Seek_RequestSubscription) TakeMessage(out *Seek_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSeek_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSeek_RequestSlice(dst, src []Seek_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Seek_RequestTypeSupport types.MessageTypeSupport = _Seek_RequestTypeSupport{}

type _Seek_RequestTypeSupport struct{}

func (t _Seek_RequestTypeSupport) New() types.Message {
	return NewSeek_Request()
}

func (t _Seek_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Seek_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Seek_Request__create())
}

func (t _Seek_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Seek_Request__destroy((*C.rosbag2_interfaces__srv__Seek_Request)(pointer_to_free))
}

func (t _Seek_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Seek_Request)
	mem := (*C.rosbag2_interfaces__srv__Seek_Request)(dst)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.time), &m.Time)
}

func (t _Seek_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Seek_Request)
	mem := (*C.rosbag2_interfaces__srv__Seek_Request)(ros2_message_buffer)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Time, unsafe.Pointer(&mem.time))
}

func (t _Seek_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Seek_Request())
}

type CSeek_Request = C.rosbag2_interfaces__srv__Seek_Request
type CSeek_Request__Sequence = C.rosbag2_interfaces__srv__Seek_Request__Sequence

func Seek_Request__Sequence_to_Go(goSlice *[]Seek_Request, cSlice CSeek_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Seek_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Seek_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Seek_Request__Sequence_to_C(cSlice *CSeek_Request__Sequence, goSlice []Seek_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Seek_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Seek_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Seek_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Seek_Request__Array_to_Go(goSlice []Seek_Request, cSlice []CSeek_Request) {
	for i := 0; i < len(cSlice); i++ {
		Seek_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Seek_Request__Array_to_C(cSlice []CSeek_Request, goSlice []Seek_Request) {
	for i := 0; i < len(goSlice); i++ {
		Seek_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
