// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/seek.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/Seek", SeekTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/Seek", SeekTypeSupport)
}

type _SeekTypeSupport struct {}

func (s _SeekTypeSupport) Request() types.MessageTypeSupport {
	return Seek_RequestTypeSupport
}

func (s _SeekTypeSupport) Response() types.MessageTypeSupport {
	return Seek_ResponseTypeSupport
}

func (s _SeekTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__Seek())
}

// Modifying this variable is undefined behavior.
var SeekTypeSupport types.ServiceTypeSupport = _SeekTypeSupport{}

// SeekClient wraps rclgo.Client to provide type safe helper
// functions
type SeekClient struct {
	*rclgo.Client
}

// NewSeekClient creates and returns a new client for the
// Seek
func NewSeekClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SeekClient, error) {
	client, err := node.NewClient(serviceName, SeekTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SeekClient{client}, nil
}

func (s *SeekClient) Send(ctx context.Context, req *Seek_Request) (*Seek_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Seek_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SeekServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SeekServiceResponseSender) SendResponse(resp *Seek_Response) error {
	return s.sender.SendResponse(resp)
}

type SeekServiceRequestHandler func(*rclgo.ServiceInfo, *Seek_Request, SeekServiceResponseSender)

// SeekService wraps rclgo.Service to provide type safe helper
// functions
type SeekService struct {
	*rclgo.Service
}

// NewSeekService creates and returns a new service for the
// Seek
func NewSeekService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SeekServiceRequestHandler) (*SeekService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*Seek_Request)
		responseSender := SeekServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SeekTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SeekService{service}, nil
}