// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/set_rate.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/SetRate", SetRateTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/SetRate", SetRateTypeSupport)
}

type _SetRateTypeSupport struct {}

func (s _SetRateTypeSupport) Request() types.MessageTypeSupport {
	return SetRate_RequestTypeSupport
}

func (s _SetRateTypeSupport) Response() types.MessageTypeSupport {
	return SetRate_ResponseTypeSupport
}

func (s _SetRateTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__SetRate())
}

// Modifying this variable is undefined behavior.
var SetRateTypeSupport types.ServiceTypeSupport = _SetRateTypeSupport{}

// SetRateClient wraps rclgo.Client to provide type safe helper
// functions
type SetRateClient struct {
	*rclgo.Client
}

// NewSetRateClient creates and returns a new client for the
// SetRate
func NewSetRateClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SetRateClient, error) {
	client, err := node.NewClient(serviceName, SetRateTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetRateClient{client}, nil
}

func (s *SetRateClient) Send(ctx context.Context, req *SetRate_Request) (*SetRate_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetRate_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetRateServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SetRateServiceResponseSender) SendResponse(resp *SetRate_Response) error {
	return s.sender.SendResponse(resp)
}

type SetRateServiceRequestHandler func(*rclgo.ServiceInfo, *SetRate_Request, SetRateServiceResponseSender)

// SetRateService wraps rclgo.Service to provide type safe helper
// functions
type SetRateService struct {
	*rclgo.Service
}

// NewSetRateService creates and returns a new service for the
// SetRate
func NewSetRateService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SetRateServiceRequestHandler) (*SetRateService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SetRate_Request)
		responseSender := SetRateServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetRateTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetRateService{service}, nil
}