// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/set_rate.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/SetRate_Response", SetRate_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/SetRate_Response", SetRate_ResponseTypeSupport)
}

type SetRate_Response struct {
	Success bool `yaml:"success"`// true if valid rate (> 0) was set
}

// NewSetRate_Response creates a new SetRate_Response with default values.
func NewSetRate_Response() *SetRate_Response {
	self := SetRate_Response{}
	self.SetDefaults()
	return &self
}

func (t *SetRate_Response) Clone() *SetRate_Response {
	c := &SetRate_Response{}
	c.Success = t.Success
	return c
}

func (t *SetRate_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetRate_Response) SetDefaults() {
	t.Success = false
}

func (t *SetRate_Response) GetTypeSupport() types.MessageTypeSupport {
	return SetRate_ResponseTypeSupport
}

// SetRate_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetRate_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSetRate_ResponsePublisher creates and returns a new publisher for the
// SetRate_Response
func NewSetRate_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetRate_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetRate_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetRate_ResponsePublisher{pub}, nil
}

func (p *SetRate_ResponsePublisher) Publish(msg *SetRate_Response) error {
	return p.Publisher.Publish(msg)
}

// SetRate_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetRate_ResponseSubscription struct {
	*rclgo.Subscription
}

// SetRate_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SetRate_ResponseSubscription.
type SetRate_ResponseSubscriptionCallback func(msg *SetRate_Response, info *rclgo.MessageInfo, err error)

// NewSetRate_ResponseSubscription creates and returns a new subscription for the
// SetRate_Response
func NewSetRate_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetRate_ResponseSubscriptionCallback) (*SetRate_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetRate_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetRate_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetRate_ResponseSubscription{sub}, nil
}

func (s *SetRate_ResponseSubscription) TakeMessage(out *SetRate_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetRate_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetRate_ResponseSlice(dst, src []SetRate_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetRate_ResponseTypeSupport types.MessageTypeSupport = _SetRate_ResponseTypeSupport{}

type _SetRate_ResponseTypeSupport struct{}

func (t _SetRate_ResponseTypeSupport) New() types.Message {
	return NewSetRate_Response()
}

func (t _SetRate_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__SetRate_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__SetRate_Response__create())
}

func (t _SetRate_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__SetRate_Response__destroy((*C.rosbag2_interfaces__srv__SetRate_Response)(pointer_to_free))
}

func (t _SetRate_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetRate_Response)
	mem := (*C.rosbag2_interfaces__srv__SetRate_Response)(dst)
	mem.success = C.bool(m.Success)
}

func (t _SetRate_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetRate_Response)
	mem := (*C.rosbag2_interfaces__srv__SetRate_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
}

func (t _SetRate_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__SetRate_Response())
}

type CSetRate_Response = C.rosbag2_interfaces__srv__SetRate_Response
type CSetRate_Response__Sequence = C.rosbag2_interfaces__srv__SetRate_Response__Sequence

func SetRate_Response__Sequence_to_Go(goSlice *[]SetRate_Response, cSlice CSetRate_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetRate_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetRate_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetRate_Response__Sequence_to_C(cSlice *CSetRate_Response__Sequence, goSlice []SetRate_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__SetRate_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__SetRate_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetRate_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetRate_Response__Array_to_Go(goSlice []SetRate_Response, cSlice []CSetRate_Response) {
	for i := 0; i < len(cSlice); i++ {
		SetRate_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetRate_Response__Array_to_C(cSlice []CSetRate_Response, goSlice []SetRate_Response) {
	for i := 0; i < len(goSlice); i++ {
		SetRate_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
