// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/snapshot.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Snapshot_Response", Snapshot_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Snapshot_Response", Snapshot_ResponseTypeSupport)
}

type Snapshot_Response struct {
	Success bool `yaml:"success"`
}

// NewSnapshot_Response creates a new Snapshot_Response with default values.
func NewSnapshot_Response() *Snapshot_Response {
	self := Snapshot_Response{}
	self.SetDefaults()
	return &self
}

func (t *Snapshot_Response) Clone() *Snapshot_Response {
	c := &Snapshot_Response{}
	c.Success = t.Success
	return c
}

func (t *Snapshot_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Snapshot_Response) SetDefaults() {
	t.Success = false
}

func (t *Snapshot_Response) GetTypeSupport() types.MessageTypeSupport {
	return Snapshot_ResponseTypeSupport
}

// Snapshot_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Snapshot_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSnapshot_ResponsePublisher creates and returns a new publisher for the
// Snapshot_Response
func NewSnapshot_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Snapshot_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, Snapshot_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Snapshot_ResponsePublisher{pub}, nil
}

func (p *Snapshot_ResponsePublisher) Publish(msg *Snapshot_Response) error {
	return p.Publisher.Publish(msg)
}

// Snapshot_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Snapshot_ResponseSubscription struct {
	*rclgo.Subscription
}

// Snapshot_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Snapshot_ResponseSubscription.
type Snapshot_ResponseSubscriptionCallback func(msg *Snapshot_Response, info *rclgo.MessageInfo, err error)

// NewSnapshot_ResponseSubscription creates and returns a new subscription for the
// Snapshot_Response
func NewSnapshot_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Snapshot_ResponseSubscriptionCallback) (*Snapshot_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Snapshot_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Snapshot_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Snapshot_ResponseSubscription{sub}, nil
}

func (s *Snapshot_ResponseSubscription) TakeMessage(out *Snapshot_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSnapshot_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSnapshot_ResponseSlice(dst, src []Snapshot_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Snapshot_ResponseTypeSupport types.MessageTypeSupport = _Snapshot_ResponseTypeSupport{}

type _Snapshot_ResponseTypeSupport struct{}

func (t _Snapshot_ResponseTypeSupport) New() types.Message {
	return NewSnapshot_Response()
}

func (t _Snapshot_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Snapshot_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Snapshot_Response__create())
}

func (t _Snapshot_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Snapshot_Response__destroy((*C.rosbag2_interfaces__srv__Snapshot_Response)(pointer_to_free))
}

func (t _Snapshot_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Snapshot_Response)
	mem := (*C.rosbag2_interfaces__srv__Snapshot_Response)(dst)
	mem.success = C.bool(m.Success)
}

func (t _Snapshot_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Snapshot_Response)
	mem := (*C.rosbag2_interfaces__srv__Snapshot_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
}

func (t _Snapshot_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Snapshot_Response())
}

type CSnapshot_Response = C.rosbag2_interfaces__srv__Snapshot_Response
type CSnapshot_Response__Sequence = C.rosbag2_interfaces__srv__Snapshot_Response__Sequence

func Snapshot_Response__Sequence_to_Go(goSlice *[]Snapshot_Response, cSlice CSnapshot_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Snapshot_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Snapshot_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Snapshot_Response__Sequence_to_C(cSlice *CSnapshot_Response__Sequence, goSlice []Snapshot_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Snapshot_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Snapshot_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Snapshot_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Snapshot_Response__Array_to_Go(goSlice []Snapshot_Response, cSlice []CSnapshot_Response) {
	for i := 0; i < len(cSlice); i++ {
		Snapshot_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Snapshot_Response__Array_to_C(cSlice []CSnapshot_Response, goSlice []Snapshot_Response) {
	for i := 0; i < len(goSlice); i++ {
		Snapshot_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
