// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/snapshot.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/Snapshot", SnapshotTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/Snapshot", SnapshotTypeSupport)
}

type _SnapshotTypeSupport struct {}

func (s _SnapshotTypeSupport) Request() types.MessageTypeSupport {
	return Snapshot_RequestTypeSupport
}

func (s _SnapshotTypeSupport) Response() types.MessageTypeSupport {
	return Snapshot_ResponseTypeSupport
}

func (s _SnapshotTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__Snapshot())
}

// Modifying this variable is undefined behavior.
var SnapshotTypeSupport types.ServiceTypeSupport = _SnapshotTypeSupport{}

// SnapshotClient wraps rclgo.Client to provide type safe helper
// functions
type SnapshotClient struct {
	*rclgo.Client
}

// NewSnapshotClient creates and returns a new client for the
// Snapshot
func NewSnapshotClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SnapshotClient, error) {
	client, err := node.NewClient(serviceName, SnapshotTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SnapshotClient{client}, nil
}

func (s *SnapshotClient) Send(ctx context.Context, req *Snapshot_Request) (*Snapshot_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Snapshot_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SnapshotServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SnapshotServiceResponseSender) SendResponse(resp *Snapshot_Response) error {
	return s.sender.SendResponse(resp)
}

type SnapshotServiceRequestHandler func(*rclgo.ServiceInfo, *Snapshot_Request, SnapshotServiceResponseSender)

// SnapshotService wraps rclgo.Service to provide type safe helper
// functions
type SnapshotService struct {
	*rclgo.Service
}

// NewSnapshotService creates and returns a new service for the
// Snapshot
func NewSnapshotService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SnapshotServiceRequestHandler) (*SnapshotService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*Snapshot_Request)
		responseSender := SnapshotServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SnapshotTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SnapshotService{service}, nil
}